POST http://localhost:3333/api/createUser
Content-Type: application/json

{
  "username": "luka2",
  "password": "123",
  "name": "content",
  "email": "luka@gmail"
}

###

GET http://localhost:3333/api/getAllUsers