@startuml

class BlogEntries {
- Id: Integer
--

# Author: String

+ Title: String
+ Description: String
+ CreationDate: Date
+ EditDates: Date[]
+ ImpressionCount: Integer
+ Content: String
+ CommentsAllowed: Boolean
+ BlogCategory: String
}

class BlogUsers {
- Username: String
--

+ Name: String
+ Email: String
+ Password: String
}

class BlogComments {
- Id: Integer
--

# EntryId: Integer
# author: String

+ content: String
}


BlogUsers -right- BlogEntries
BlogComments -up- BlogEntries

BlogUsers -- BlogComments
@enduml